
grobid:
  server: "http://falcon.nims.go.jp/superconductors/unstable"
#  server: "http://localhost:8072" # https://github.com/lfoppiano/grobid-superconductors
  url_mapping:
    processPDF_disableLinking: "/service/process/pdf?disableLinking=true"
    processPDF: "/service/process/pdf"
    processText: "/service/process/text"
    processJson: "/service/process/json"
    linker: "/service/linker/link"
    ping: "/"

batch_size: 1000

# Seconds to wait when receiving a 503 response
sleep_time: 10
coordinates: null

# Max number of retry
max_retry: 3
